services:
  web:
    build: .
    ports:
      # 服务器的 3000 端口已被占用，我们把对外端口改到 3001
      - "3001:3000"
    volumes:
      # 持久化数据库文件，防止容器重启丢失数据
      - ./prisma/sqlite:/app/prisma/sqlite
      # 挂载密码目录
      - ./secrets:/app/secrets
    environment:
      - DATABASE_URL=file:./sqlite/dev.db
    restart: unless-stopped
